# Generated by Django 5.2.4 on 2025-08-09 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_tipmodel_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipmodel',
            name='downvoter',
            field=models.ManyToManyField(related_name='downvoter_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipmodel',
            name='upvoter',
            field=models.ManyToManyField(related_name='upvoter_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
