# Generated by Django 5.2.4 on 2025-08-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_tipmodel_downvoter_tipmodel_upvoter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipmodel',
            options={'permissions': [('can_downvote', 'Can Downvote')]},
        ),
    ]
