# Generated by Django 5.2.3 on 2025-07-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField()),
                ('diameter', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.FloatField()),
                ('terrain', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=32)),
                ('hair_color', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name')),
            ],
        ),
    ]
